geozero-shp release with deprecation message
georust/geozero pull request #234
Opened 2024-08-28 20:14 UTC by pka

Should be released & merged before #233

2024-08-28 20:15 UTC, kylebarron approved these changes

2024-08-29 21:43 UTC, michaelkirk requested changes
Can you include a module level declaration so that people can see it in their compiler output, since people often don't read documentation:

Something like:
```
#![deprecated(note = "The geozero_shp crate has been deprecated. Instead, use geozero's built-in shapefile feature")]
```

2024-08-29 21:44 UTC, michaelkirk commented on geozero-shp/Cargo.toml
> -version = "0.5.0"
I think this should be a patch bump - we're not breaking anything right?

2024-08-29 22:27 UTC, pka commented
Test fails because of clippy complaints... Will force merge it when both PRs are ready.

2024-08-30 22:25 UTC, michaelkirk approved these changes

2024-08-30 22:45 UTC, merged

2024-08-30 22:46 UTC, pka commented
Note to self: Release to crates.io just after next geozero release!

2024-08-30 23:51 UTC, michaelkirk commented
Will we have to pin to a specific (old) version of geozero for this geozero_shp release? Currently it's using "workspace"